/*-- VOTOS DOS SENADORES PROPORCIONALMENTE*/
/*3.0*/

SELECT NOME,
((CASE WHEN Sim > 0 THEN SUM(Sim) END)+(CASE WHEN Nao > 0 THEN SUM(Nao) END)) AS TOTAL /*Add todos os votos que sao computados (pode tambem add pra saber os votos nao computiveis)*/
FROM (
SELECT
SEN.nome
, COUNT(CASE WHEN VT.idTIPO_VOTO='1' THEN TV.SIGLA END) AS "MIS"
, COUNT(CASE WHEN VT.idTIPO_VOTO='2' THEN TV.SIGLA END) AS "P-NRV"
, COUNT(CASE WHEN VT.idTIPO_VOTO='3' THEN TV.SIGLA END) AS "P-OD"
, COUNT(CASE WHEN VT.idTIPO_VOTO='4' THEN TV.SIGLA END) AS "REP"
, COUNT(CASE WHEN VT.idTIPO_VOTO='5' THEN TV.SIGLA END) AS "Ncom"
, COUNT(CASE WHEN VT.idTIPO_VOTO='6' THEN TV.SIGLA END) AS "AP"
, COUNT(CASE WHEN VT.idTIPO_VOTO='7' THEN TV.SIGLA END) AS "LA"
, COUNT(CASE WHEN VT.idTIPO_VOTO='8' THEN TV.SIGLA END) AS "LAP"
, COUNT(CASE WHEN VT.idTIPO_VOTO='9' THEN TV.SIGLA END) AS "LC"
, COUNT(CASE WHEN VT.idTIPO_VOTO='10' THEN TV.SIGLA END) AS "LS"
, COUNT(CASE WHEN VT.idTIPO_VOTO='11' THEN TV.SIGLA END) AS "LG"
, COUNT(CASE WHEN VT.idTIPO_VOTO='12' THEN TV.SIGLA END) AS "NA"
, COUNT(CASE WHEN VT.idTIPO_VOTO='13' THEN TV.SIGLA END) AS "MERC"
, COUNT(CASE WHEN VT.idTIPO_VOTO='14' THEN TV.SIGLA END) AS "Presidente (art. 51 RISF)"
, COUNT(CASE WHEN VT.idTIPO_VOTO='15' THEN TV.SIGLA END) AS "Nao"
, COUNT(CASE WHEN VT.idTIPO_VOTO='16' THEN TV.SIGLA END) AS "Sim"
, COUNT(CASE WHEN VT.idTIPO_VOTO='17' THEN TV.SIGLA END) AS "Abstencao"
, COUNT(CASE WHEN VT.idTIPO_VOTO='18' THEN TV.SIGLA END) AS "Votou"
, COUNT(CASE WHEN VT.idTIPO_VOTO='19' THEN TV.SIGLA END) AS "LP"
, COUNT(CASE WHEN VT.idTIPO_VOTO='20' THEN TV.SIGLA END) AS "LL"
, COUNT(CASE WHEN VT.idTIPO_VOTO='21' THEN TV.SIGLA END) AS "LN"
, COUNT(CASE WHEN VT.idTIPO_VOTO='22' THEN TV.SIGLA END) AS "Impedido (art.306 RISF)"
, COUNT(CASE WHEN VT.idTIPO_VOTO='23' THEN TV.SIGLA END) AS "Obstrucao"
, COUNT(CASE WHEN VT.idTIPO_VOTO='24' THEN TV.SIGLA END) AS "PSF"
FROM base_senado.voto VT
INNER JOIN base_senado.senador SEN 	ON VT.idSENADOR = SEN.idSENADOR
INNER JOIN base_senado.sequencia SEQ 	ON VT.idSEQUENCIA = SEQ.idSEQUENCIA
INNER JOIN base_senado.tipo_voto TV 	ON VT.idTIPO_VOTO = TV.idTIPO_VOTO
INNER JOIN base_senado.tipo_sessao TS 	ON SEQ.TIPO_SESSAO = TS.idTIPO_SESSAO
GROUP BY SEN.NOME
ORDER BY SEN.NOME

) AS temp
GROUP BY NOME;


/*-------------- FEITO --------------*/


SELECT
        NOME,
        (CASE WHEN Sim > 0 THEN SUM(Sim) END) AS TOTAL_VOTOS_SIM,
        (CASE WHEN Nao > 0 THEN SUM(Nao) END) AS TOTAL_VOTOS_NAO,
		(CASE WHEN (Sim > 0) OR (Nao > 0) OR (MIS > 0) OR (REP > 0) OR (AP > 0) OR (LC > 0) OR (NA > 0) OR (MERC > 0) OR (LP > 0) OR (LL > 0) OR (LN > 0) OR (Impedido > 0) OR (Obstrucao > 0) OR (PSF > 0) THEN (SUM(Sim)+SUM(Nao)+SUM(MIS)+SUM(REP)+SUM(AP)+SUM(LC)+SUM(NA)+SUM(MERC)+SUM(LP)+SUM(LL)+SUM(LN)+SUM(Impedido)+SUM(Obstrucao)+SUM(PSF)) END) AS TOTAL_MAIS_VOTARAM,
        (CASE WHEN (Ncom > 0) OR (LS > 0) OR (LG > 0) OR (LA > 0) OR (LAP > 0) THEN (SUM(Ncom)+SUM(LS)+SUM(LG)+SUM(LA)+SUM(LAP)) END) AS TOTAL_AUSENCIA
FROM (
        SELECT
                SEN.nome
                , COUNT(CASE WHEN VT.idTIPO_VOTO='1' THEN TV.SIGLA END) AS "MIS"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='2' THEN TV.SIGLA END) AS "P_NRV"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='3' THEN TV.SIGLA END) AS "P_OD"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='4' THEN TV.SIGLA END) AS "REP"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='5' THEN TV.SIGLA END) AS "Ncom"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='6' THEN TV.SIGLA END) AS "AP"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='7' THEN TV.SIGLA END) AS "LA"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='8' THEN TV.SIGLA END) AS "LAP"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='9' THEN TV.SIGLA END) AS "LC"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='10' THEN TV.SIGLA END) AS "LS"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='11' THEN TV.SIGLA END) AS "LG"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='12' THEN TV.SIGLA END) AS "NA"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='13' THEN TV.SIGLA END) AS "MERC"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='14' THEN TV.SIGLA END) AS "Presidente"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='15' THEN TV.SIGLA END) AS "Nao"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='16' THEN TV.SIGLA END) AS "Sim"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='17' THEN TV.SIGLA END) AS "Abstencao"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='18' THEN TV.SIGLA END) AS "Votou"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='19' THEN TV.SIGLA END) AS "LP"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='20' THEN TV.SIGLA END) AS "LL"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='21' THEN TV.SIGLA END) AS "LN"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='22' THEN TV.SIGLA END) AS "Impedido"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='23' THEN TV.SIGLA END) AS "Obstrucao"
                , COUNT(CASE WHEN VT.idTIPO_VOTO='24' THEN TV.SIGLA END) AS "PSF"
FROM base_senado.voto VT
INNER JOIN base_senado.senador SEN 	ON VT.idSENADOR = SEN.idSENADOR
INNER JOIN base_senado.sequencia SEQ 	ON VT.idSEQUENCIA = SEQ.idSEQUENCIA
INNER JOIN base_senado.tipo_voto TV 	ON VT.idTIPO_VOTO = TV.idTIPO_VOTO
INNER JOIN base_senado.tipo_sessao TS 	ON SEQ.TIPO_SESSAO = TS.idTIPO_SESSAO
GROUP BY SEN.NOME
ORDER BY SEN.NOME
) AS temp
GROUP BY NOME;