/*1.2.2*/
SELECT DISTINCT
TV.idTIPO_VOTO AS VOTO,
CONCAT(', COUNT(CASE WHEN VT.idTIPO_VOTO=''',TV.idTIPO_VOTO,''' THEN TV.SIGLA END) AS "',TV.idTIPO_VOTO,'"') AS TEXTO
FROM base_senado.tipo_voto TV 
ORDER BY 1, 2;

SELECT
SEN.nome AS SENADOR
, COUNT(CASE WHEN VT.idTIPO_VOTO='1' THEN TV.SIGLA END) AS "MIS"
, COUNT(CASE WHEN VT.idTIPO_VOTO='2' THEN TV.SIGLA END) AS "P-NRV"
, COUNT(CASE WHEN VT.idTIPO_VOTO='3' THEN TV.SIGLA END) AS "P-OD"
, COUNT(CASE WHEN VT.idTIPO_VOTO='4' THEN TV.SIGLA END) AS "REP"
, COUNT(CASE WHEN VT.idTIPO_VOTO='5' THEN TV.SIGLA END) AS "Ncom"
, COUNT(CASE WHEN VT.idTIPO_VOTO='6' THEN TV.SIGLA END) AS "AP"
, COUNT(CASE WHEN VT.idTIPO_VOTO='7' THEN TV.SIGLA END) AS "LA"
, COUNT(CASE WHEN VT.idTIPO_VOTO='8' THEN TV.SIGLA END) AS "LAP"
, COUNT(CASE WHEN VT.idTIPO_VOTO='9' THEN TV.SIGLA END) AS "LC"
, COUNT(CASE WHEN VT.idTIPO_VOTO='10' THEN TV.SIGLA END) AS "LS"
, COUNT(CASE WHEN VT.idTIPO_VOTO='11' THEN TV.SIGLA END) AS "LG"
, COUNT(CASE WHEN VT.idTIPO_VOTO='12' THEN TV.SIGLA END) AS "NA"
, COUNT(CASE WHEN VT.idTIPO_VOTO='13' THEN TV.SIGLA END) AS "MERC"
, COUNT(CASE WHEN VT.idTIPO_VOTO='14' THEN TV.SIGLA END) AS "Presidente (art. 51 RISF)"
, COUNT(CASE WHEN VT.idTIPO_VOTO='15' THEN TV.SIGLA END) AS "Não"
, COUNT(CASE WHEN VT.idTIPO_VOTO='16' THEN TV.SIGLA END) AS "Sim"
, COUNT(CASE WHEN VT.idTIPO_VOTO='17' THEN TV.SIGLA END) AS "Abstencao"
, COUNT(CASE WHEN VT.idTIPO_VOTO='18' THEN TV.SIGLA END) AS "Votou"
, COUNT(CASE WHEN VT.idTIPO_VOTO='19' THEN TV.SIGLA END) AS "LP"
, COUNT(CASE WHEN VT.idTIPO_VOTO='20' THEN TV.SIGLA END) AS "LL"
, COUNT(CASE WHEN VT.idTIPO_VOTO='21' THEN TV.SIGLA END) AS "LN"
, COUNT(CASE WHEN VT.idTIPO_VOTO='22' THEN TV.SIGLA END) AS "Impedido (art.306 RISF)"
, COUNT(CASE WHEN VT.idTIPO_VOTO='23' THEN TV.SIGLA END) AS "Obstrucao"
, COUNT(CASE WHEN VT.idTIPO_VOTO='24' THEN TV.SIGLA END) AS "PSF"
FROM base_senado.voto VT
INNER JOIN base_senado.senador SEN 	ON VT.idSENADOR = SEN.idSENADOR
INNER JOIN base_senado.sequencia SEQ 	ON VT.idSEQUENCIA = SEQ.idSEQUENCIA
INNER JOIN base_senado.tipo_voto TV 	ON VT.idTIPO_VOTO = TV.idTIPO_VOTO
INNER JOIN base_senado.tipo_sessao TS 	ON SEQ.TIPO_SESSAO = TS.idTIPO_SESSAO
GROUP BY SEN.NOME
ORDER BY SEN.NOME;