/*2.2*/
SELECT DISTINCT
SEN.NOME AS SENADOR,
CONCAT(', MAX(CASE WHEN SEN.idSENADOR=',SEN.idSENADOR,' THEN TV.SIGLA END) AS "',SEN.NOME,' - ',SEN.partido,'/',SEN.uf,'"') AS TEXTO
FROM base_senado.senador SEN
ORDER BY 1, 2;


SELECT
SEQ.MATERIA
, MAX(CASE WHEN SEN.idSENADOR=1 THEN TV.SIGLA END) AS "Acir Gurgacz - PDT/RO"
, MAX(CASE WHEN SEN.idSENADOR=8 THEN TV.SIGLA END) AS "Aécio Neves - PSDB/MG"
, MAX(CASE WHEN SEN.idSENADOR=100 THEN TV.SIGLA END) AS "Airton Sandoval - PMDB/SP"
, MAX(CASE WHEN SEN.idSENADOR=2 THEN TV.SIGLA END) AS "Aloysio Nunes Ferreira - PSDB/SP"
, MAX(CASE WHEN SEN.idSENADOR=3 THEN TV.SIGLA END) AS "Alvaro Dias - PSDB/PR"
, MAX(CASE WHEN SEN.idSENADOR=4 THEN TV.SIGLA END) AS "Ana Amélia - PP/RS"
, MAX(CASE WHEN SEN.idSENADOR=84 THEN TV.SIGLA END) AS "Ângela Portela - PT/RR"
, MAX(CASE WHEN SEN.idSENADOR=85 THEN TV.SIGLA END) AS "Angela Portela - PT/RR"
, MAX(CASE WHEN SEN.idSENADOR=5 THEN TV.SIGLA END) AS "Antonio Anastasia - PSDB/MG"
, MAX(CASE WHEN SEN.idSENADOR=6 THEN TV.SIGLA END) AS "Antonio Carlos Valadares - PSB/SE"
, MAX(CASE WHEN SEN.idSENADOR=86 THEN TV.SIGLA END) AS "Armando Monteiro - PTB/PE"
, MAX(CASE WHEN SEN.idSENADOR=7 THEN TV.SIGLA END) AS "Ataídes Oliveira - PSDB/TO"
, MAX(CASE WHEN SEN.idSENADOR=9 THEN TV.SIGLA END) AS "Benedito de Lira - PP/AL"
, MAX(CASE WHEN SEN.idSENADOR=10 THEN TV.SIGLA END) AS "Blairo Maggi - PR/MT"
, MAX(CASE WHEN SEN.idSENADOR=13 THEN TV.SIGLA END) AS "Cássio Cunha Lima - PSDB/PB"
, MAX(CASE WHEN SEN.idSENADOR=87 THEN TV.SIGLA END) AS "Cidinho Santos - PR/MT"
, MAX(CASE WHEN SEN.idSENADOR=11 THEN TV.SIGLA END) AS "Ciro Nogueira - PP/PI"
, MAX(CASE WHEN SEN.idSENADOR=12 THEN TV.SIGLA END) AS "Cristovam Buarque - PDT/DF"
, MAX(CASE WHEN SEN.idSENADOR=14 THEN TV.SIGLA END) AS "Dalirio Beber - PSDB/SC"
, MAX(CASE WHEN SEN.idSENADOR=19 THEN TV.SIGLA END) AS "Dário Berger - PMDB/SC"
, MAX(CASE WHEN SEN.idSENADOR=15 THEN TV.SIGLA END) AS "Davi Alcolumbre - DEM/AP"
, MAX(CASE WHEN SEN.idSENADOR=88 THEN TV.SIGLA END) AS "Deca - PSDB/PB"
, MAX(CASE WHEN SEN.idSENADOR=16 THEN TV.SIGLA END) AS "Delcídio do Amaral - PT/MS"
, MAX(CASE WHEN SEN.idSENADOR=17 THEN TV.SIGLA END) AS "Donizeti Nogueira - PT/TO"
, MAX(CASE WHEN SEN.idSENADOR=18 THEN TV.SIGLA END) AS "Douglas Cintra - PTB/PE"
, MAX(CASE WHEN SEN.idSENADOR=20 THEN TV.SIGLA END) AS "Edison Lobão - PMDB/MA"
, MAX(CASE WHEN SEN.idSENADOR=21 THEN TV.SIGLA END) AS "Eduardo Amorim - PSC/SE"
, MAX(CASE WHEN SEN.idSENADOR=89 THEN TV.SIGLA END) AS "Eduardo Braga - PMDB/AM"
, MAX(CASE WHEN SEN.idSENADOR=90 THEN TV.SIGLA END) AS "Eduardo Lopes - PRB/RJ"
, MAX(CASE WHEN SEN.idSENADOR=102 THEN TV.SIGLA END) AS "Elber Batalha - PSB/SE"
, MAX(CASE WHEN SEN.idSENADOR=22 THEN TV.SIGLA END) AS "Elmano Férrer - PTB/PI"
, MAX(CASE WHEN SEN.idSENADOR=23 THEN TV.SIGLA END) AS "Eunício Oliveira - PMDB/CE"
, MAX(CASE WHEN SEN.idSENADOR=28 THEN TV.SIGLA END) AS "Fátima Bezerra - PT/RN"
, MAX(CASE WHEN SEN.idSENADOR=24 THEN TV.SIGLA END) AS "Fernando Bezerra Coelho - PSB/PE"
, MAX(CASE WHEN SEN.idSENADOR=25 THEN TV.SIGLA END) AS "Fernando Collor - PTB/AL"
, MAX(CASE WHEN SEN.idSENADOR=26 THEN TV.SIGLA END) AS "Fernando Ribeiro - PMDB/PA"
, MAX(CASE WHEN SEN.idSENADOR=27 THEN TV.SIGLA END) AS "Flexa Ribeiro - PSDB/PA"
, MAX(CASE WHEN SEN.idSENADOR=29 THEN TV.SIGLA END) AS "Garibaldi Alves Filho - PMDB/RN"
, MAX(CASE WHEN SEN.idSENADOR=91 THEN TV.SIGLA END) AS "Gilberto Piselo - PDT/RO"
, MAX(CASE WHEN SEN.idSENADOR=30 THEN TV.SIGLA END) AS "Gladson Cameli - PP/AC"
, MAX(CASE WHEN SEN.idSENADOR=31 THEN TV.SIGLA END) AS "Gleisi Hoffmann - PT/PR"
, MAX(CASE WHEN SEN.idSENADOR=33 THEN TV.SIGLA END) AS "Hélio José - PSD/DF"
, MAX(CASE WHEN SEN.idSENADOR=32 THEN TV.SIGLA END) AS "Humberto Costa - PT/PE"
, MAX(CASE WHEN SEN.idSENADOR=34 THEN TV.SIGLA END) AS "Ivo Cassol - PP/RO"
, MAX(CASE WHEN SEN.idSENADOR=35 THEN TV.SIGLA END) AS "Jader Barbalho - PMDB/PA"
, MAX(CASE WHEN SEN.idSENADOR=42 THEN TV.SIGLA END) AS "João Alberto Souza - PMDB/MA"
, MAX(CASE WHEN SEN.idSENADOR=43 THEN TV.SIGLA END) AS "João Capiberibe - PSB/AP"
, MAX(CASE WHEN SEN.idSENADOR=36 THEN TV.SIGLA END) AS "Jorge Viana - PT/AC"
, MAX(CASE WHEN SEN.idSENADOR=37 THEN TV.SIGLA END) AS "José Agripino - DEM/RN"
, MAX(CASE WHEN SEN.idSENADOR=92 THEN TV.SIGLA END) AS "José Aníbal - PSDB/SP"
, MAX(CASE WHEN SEN.idSENADOR=38 THEN TV.SIGLA END) AS "José Maranhão - PMDB/PB"
, MAX(CASE WHEN SEN.idSENADOR=39 THEN TV.SIGLA END) AS "José Medeiros - PPS/MT"
, MAX(CASE WHEN SEN.idSENADOR=40 THEN TV.SIGLA END) AS "José Pimentel - PT/CE"
, MAX(CASE WHEN SEN.idSENADOR=41 THEN TV.SIGLA END) AS "José Serra - PSDB/SP"
, MAX(CASE WHEN SEN.idSENADOR=93 THEN TV.SIGLA END) AS "Kátia Abreu - PMDB/TO"
, MAX(CASE WHEN SEN.idSENADOR=44 THEN TV.SIGLA END) AS "Lasier Martins - PDT/RS"
, MAX(CASE WHEN SEN.idSENADOR=47 THEN TV.SIGLA END) AS "Lídice da Mata - PSB/BA"
, MAX(CASE WHEN SEN.idSENADOR=45 THEN TV.SIGLA END) AS "Lindbergh Farias - PT/RJ"
, MAX(CASE WHEN SEN.idSENADOR=48 THEN TV.SIGLA END) AS "Lúcia Vânia - PSDB/GO"
, MAX(CASE WHEN SEN.idSENADOR=46 THEN TV.SIGLA END) AS "Luiz Henrique - PMDB/SC"
, MAX(CASE WHEN SEN.idSENADOR=49 THEN TV.SIGLA END) AS "Magno Malta - PR/ES"
, MAX(CASE WHEN SEN.idSENADOR=50 THEN TV.SIGLA END) AS "Marcelo Crivella - PRB/RJ"
, MAX(CASE WHEN SEN.idSENADOR=51 THEN TV.SIGLA END) AS "Maria do Carmo Alves - DEM/SE"
, MAX(CASE WHEN SEN.idSENADOR=52 THEN TV.SIGLA END) AS "Marta Suplicy - PT/SP"
, MAX(CASE WHEN SEN.idSENADOR=53 THEN TV.SIGLA END) AS "Omar Aziz - PSD/AM"
, MAX(CASE WHEN SEN.idSENADOR=54 THEN TV.SIGLA END) AS "Otto Alencar - PSD/BA"
, MAX(CASE WHEN SEN.idSENADOR=94 THEN TV.SIGLA END) AS "Pastor Valadares - PDT/RO"
, MAX(CASE WHEN SEN.idSENADOR=55 THEN TV.SIGLA END) AS "Paulo Bauer - PSDB/SC"
, MAX(CASE WHEN SEN.idSENADOR=56 THEN TV.SIGLA END) AS "Paulo Paim - PT/RS"
, MAX(CASE WHEN SEN.idSENADOR=57 THEN TV.SIGLA END) AS "Paulo Rocha - PT/PA"
, MAX(CASE WHEN SEN.idSENADOR=95 THEN TV.SIGLA END) AS "Pedro Chaves - PSC/MS"
, MAX(CASE WHEN SEN.idSENADOR=96 THEN TV.SIGLA END) AS "Pinto Itamaraty - PSDB/MA"
, MAX(CASE WHEN SEN.idSENADOR=58 THEN TV.SIGLA END) AS "Raimundo Lira - PMDB/PB"
, MAX(CASE WHEN SEN.idSENADOR=59 THEN TV.SIGLA END) AS "Randolfe Rodrigues - PSOL/AP"
, MAX(CASE WHEN SEN.idSENADOR=60 THEN TV.SIGLA END) AS "Regina Sousa - PT/PI"
, MAX(CASE WHEN SEN.idSENADOR=61 THEN TV.SIGLA END) AS "Reguffe - PDT/DF"
, MAX(CASE WHEN SEN.idSENADOR=62 THEN TV.SIGLA END) AS "Renan Calheiros - PMDB/AL"
, MAX(CASE WHEN SEN.idSENADOR=63 THEN TV.SIGLA END) AS "Ricardo Ferraço - PMDB/ES"
, MAX(CASE WHEN SEN.idSENADOR=64 THEN TV.SIGLA END) AS "Ricardo Franco - DEM/SE"
, MAX(CASE WHEN SEN.idSENADOR=97 THEN TV.SIGLA END) AS "Roberto Muniz - PP/BA"
, MAX(CASE WHEN SEN.idSENADOR=65 THEN TV.SIGLA END) AS "Roberto Requião - PMDB/PR"
, MAX(CASE WHEN SEN.idSENADOR=66 THEN TV.SIGLA END) AS "Roberto Rocha - PSB/MA"
, MAX(CASE WHEN SEN.idSENADOR=68 THEN TV.SIGLA END) AS "Romário - PSB/RJ"
, MAX(CASE WHEN SEN.idSENADOR=67 THEN TV.SIGLA END) AS "Romero Jucá - PMDB/RR"
, MAX(CASE WHEN SEN.idSENADOR=69 THEN TV.SIGLA END) AS "Ronaldo Caiado - DEM/GO"
, MAX(CASE WHEN SEN.idSENADOR=70 THEN TV.SIGLA END) AS "Rose de Freitas - PMDB/ES"
, MAX(CASE WHEN SEN.idSENADOR=71 THEN TV.SIGLA END) AS "Sandra Braga - PMDB/AM"
, MAX(CASE WHEN SEN.idSENADOR=103 THEN TV.SIGLA END) AS "Sérgio de Castro - PDT/ES"
, MAX(CASE WHEN SEN.idSENADOR=73 THEN TV.SIGLA END) AS "Sérgio Petecão - PSD/AC"
, MAX(CASE WHEN SEN.idSENADOR=72 THEN TV.SIGLA END) AS "Simone Tebet - PMDB/MS"
, MAX(CASE WHEN SEN.idSENADOR=74 THEN TV.SIGLA END) AS "Tasso Jereissati - PSDB/CE"
, MAX(CASE WHEN SEN.idSENADOR=75 THEN TV.SIGLA END) AS "Telmário Mota - PDT/RR"
, MAX(CASE WHEN SEN.idSENADOR=101 THEN TV.SIGLA END) AS "Thieres Pinto - PTB/RR"
, MAX(CASE WHEN SEN.idSENADOR=76 THEN TV.SIGLA END) AS "Valdir Raupp - PMDB/RO"
, MAX(CASE WHEN SEN.idSENADOR=77 THEN TV.SIGLA END) AS "Vanessa Grazziotin - PCdoB/AM"
, MAX(CASE WHEN SEN.idSENADOR=78 THEN TV.SIGLA END) AS "Vicentinho Alves - PR/TO"
, MAX(CASE WHEN SEN.idSENADOR=98 THEN TV.SIGLA END) AS "Virginio de Carvalho - PSC/SE"
, MAX(CASE WHEN SEN.idSENADOR=79 THEN TV.SIGLA END) AS "Waldemir Moka - PMDB/MS"
, MAX(CASE WHEN SEN.idSENADOR=80 THEN TV.SIGLA END) AS "Walter Pinheiro - PT/BA"
, MAX(CASE WHEN SEN.idSENADOR=81 THEN TV.SIGLA END) AS "Wellington Fagundes - PR/MT"
, MAX(CASE WHEN SEN.idSENADOR=82 THEN TV.SIGLA END) AS "Wilder Morais - DEM/GO"
, MAX(CASE WHEN SEN.idSENADOR=99 THEN TV.SIGLA END) AS "Wirlande da Luz - PMDB/RR"
, MAX(CASE WHEN SEN.idSENADOR=83 THEN TV.SIGLA END) AS "Zeze Perrella - PDT/MG"
, SEQ.RESULTADO
FROM base_senado.voto VT
INNER JOIN base_senado.senador SEN 	ON VT.idSENADOR = SEN.idSENADOR
INNER JOIN base_senado.sequencia SEQ 	ON VT.idSEQUENCIA = SEQ.idSEQUENCIA
INNER JOIN base_senado.tipo_voto TV 	ON VT.idTIPO_VOTO = TV.idTIPO_VOTO
INNER JOIN base_senado.tipo_sessao TS 	ON SEQ.TIPO_SESSAO = TS.idTIPO_SESSAO
WHERE TS.idTIPO_SESSAO IN (1, 3) AND SEQ.RESULTADO IN ('Aprovado', 'Rejeitado') /*AND TV.idTIPO_VOTO IN (15, 16) SIM-NÃO*/ AND SEQ.materia IN ('PEC 00040/2011',
'PLC 00002/2015',
'MPV 00663/2014',
'MPV 00665/2014',
'PLS 00400/2014',
'MPV 00670/2015',
'MPV 00678/2015',
'MPV 00430/2015',
'PLC 00057/2015',
'PDS 00347/2015',
'PEC 00113/2015',
'PLC 00023/2015',
'PEC 00133/2015',
'MPV 00727/2016',
'MPV 00729/2016',
'PRS 00029/2016',
'DEN 00001/2016',
'PEC 00043/2012',
'PLC 00007/2016',
'MPV 00693/2015',
'PEC 00055/2016',
'PLS 00085/2017',
'PEC 00064/2016',
'MPV 00014/2001',
'PLC 00038/2017',
'SCD 00007/2016',
'PLS 00477/2011',
'SCD 00005/2015',
'PLS 00224/2013',
'PLC 00101/2015',
'MPV 00744/2016',
'MPV 00746/2016',
'PEC 00083/2015',
'PLC 00186/2015',
'PLS 00555/2015',
'PLS 00405/2016',
'PEC 00036/2016',
'PEC 00010/2013',
'PEC 00014/2016',
'PLC 00028/2017')
GROUP BY SEQ.MATERIA
ORDER BY SEQ.MATERIA;